typedef signed char s8_t;
typedef unsigned char u8_t;
typedef signed short s16_t;
typedef unsigned short u16_t;
typedef signed int s32_t;
typedef unsigned int u32_t;
typedef signed long sl_t;
typedef unsigned long ul_t;
typedef signed long long s64_t;
typedef unsigned long long u64_t;
